// Code generated by goctl. DO NOT EDIT.
package handler

import (
	ws "gitee.com/unitedrhino/share/websocket"
	"net/http"

	thingsdeviceinfo "lightsvr/internal/handler/things/device/info"
	"lightsvr/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterWsHandlers(server *ws.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckTokenWare, serverCtx.InitCtxsWare},
			[]rest.Route{
				{
					// 设备控制
					Method:  http.MethodPost,
					Path:    "/control",
					Handler: thingsdeviceinfo.ControlHandler(serverCtx),
				},
				{
					// 新增设备
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: thingsdeviceinfo.CreateHandler(serverCtx),
				},
				{
					// 删除设备
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: thingsdeviceinfo.DeleteHandler(serverCtx),
				},
				{
					// 更新设备
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: thingsdeviceinfo.UpdateHandler(serverCtx),
				},
			}...,
		),
		ws.WithPrefix("/api/v1/things/device/info"),
	)
}
